backend/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("statistics/", include("data_statistics.urls", namespace="data_statistics"), name="data_statistics"),
    path("", include("search_engine.urls", namespace="search_engine"), name="search_engine"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

backend/search_engine/urls.py
from django.urls import path

from .views import HomeView, CorporationView, FavoriteCorporationView, StatisticsView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("<int:corporation_number>/", CorporationView.as_view(), name="corporation"),
    path("favorite_corporation/", FavoriteCorporationView.as_view(), name="favorite_corporations"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
]

backend/search_engine/models.py
from django.db import models
from django.db.models import F

from .utils import code_validator


class Prefectures(models.Model):
    # prefectureName from xml, name of the prefecture.
    name = models.CharField(max_length=128, db_comment="Name of the prefecture.")
    # prefectureCode from xml, unique number of the prefecture.
    code = models.CharField(unique=True, max_length=2, db_comment="Unique number of the prefecture.")
    # enPrefectureName from xml, name of the prefecture in English.
    en_name = models.CharField(max_length=128, db_comment="Name of the prefecture in English.")

    created_at = models.DateTimeField(blank=True, auto_now_add=True, db_comment="Created at.")
    updated_at = models.DateTimeField(blank=True, auto_now=True, db_comment="Updated at.")

    class Meta:
        db_table = "prefectures"


class Cities(models.Model):
    # cityName from xml, name of the city.
    name = models.CharField(max_length=128, db_comment="Name of the city.")
    # cityCode from xml, unique number of the city.
    code = models.SmallIntegerField(db_comment="Unique number of the city.")
    # enCityName from xml, name of the city in English.
    en_name = models.CharField(max_length=128, blank=True, null=True, db_comment="Name of the city in English.")

    created_at = models.DateTimeField(blank=True, auto_now_add=True, db_comment="Created at.")
    updated_at = models.DateTimeField(blank=True, auto_now=True, db_comment="Updated at.")

    class Meta:
        db_table = "cities"


class Corporations(models.Model):
    # corporateNumber from xml, unique number for each company in Japan to identify it.
    number = models.CharField(unique=True, max_length=13, db_comment="Unique number for each company in Japan to identify it.")
    # process from xml, consist of 2 numbers (02, 81, 32, ...), not sure what it is.
    process = models.CharField(max_length=2, db_comment="Consist of 2 numbers (02, 81, 32, ...), not sure what it is.")
    # correct from xml, not sure what it is.
    correct = models.BooleanField(db_comment="Not sure what it is.")
    # updateDate from xml, date of update of the record in import file.
    update_date = models.DateField(db_comment="Date of update of the record in import file.")
    # changeDate from xml, date of change of the record in import file.
    change_date = models.DateField(db_comment="Date of change of the record in import file.")
    # name from xml, name of the company.
    name = models.CharField(max_length=256, db_comment="Name of the company.")
    # nameImageId from xml, image of the company name (https://www.houjin-bangou.nta.go.jp/image?imageid=<nameImageId>).
    name_image_id = models.CharField(max_length=8, blank=True, null=True, db_comment="Image of the company name (https://www.houjin-bangou.nta.go.jp/image?imageid=<nameImageId>).")
    # kind from xml, not sure what it is.
    kind = models.SmallIntegerField(db_comment="Not sure what it is.")
    # streetNumber from xml, name of the street.
    street_number = models.CharField(max_length=128, blank=True, null=True, db_comment="Name of the street.")
    # addressImageId from xml, image of the company address (https://www.houjin-bangou.nta.go.jp/image?imageid=<addressImageId>).
    address_image_id = models.CharField(max_length=8, blank=True, null=True, db_comment="Image of the company address (https://www.houjin-bangou.nta.go.jp/image?imageid=<addressImageId>).")
    # postCode from xml, postal code of the company.
    post_code = models.CharField(max_length=7, blank=True, null=True, db_comment="Postal code of the company.")
    # addressOutside from xml, address of the company outside of Japan.
    address_outside = models.CharField(max_length=512, blank=True, null=True, db_comment="Address of the company outside of Japan.")
    # addressOutsideImageId from xml, image of the company address outside of Japan (https://www.houjin-bangou.nta.go.jp/image?imageid=<addressOutsideImageId>).
    address_outside_image_id = models.CharField(max_length=8, blank=True, null=True, db_comment="Image of the company address outside of Japan (https://www.houjin-bangou.nta.go.jp/image?imageid=<addressOutsideImageId>).")
    # closeDate from xml, date of the company closing.
    close_date = models.DateField(blank=True, null=True, db_comment="Date of the company closing.")
    # closeCause from xml, cause code of the company closing.
    close_cause = models.CharField(max_length=2, blank=True, null=True, db_comment="Cause code of the company closing.")
    # successorCorporateNumber from xml, old corporate number of the company.
    successor_number = models.CharField(max_length=13, blank=True, null=True, db_comment="Old corporate number of the company.")
    # changeCause from xml, cause code of the company change.
    change_cause = models.TextField(blank=True, null=True, db_comment="Cause code of the company change.")
    # assignmentDate from xml, date of the company assignment (date of creation of corporate number).
    assignment_date = models.DateField(db_comment="Date of the company assignment (date of creation of corporate number).")
    # latest from xml, not sure what it is.
    latest = models.BooleanField(db_comment="Not sure what it is.")
    # enName from xml, name of the company in English.
    en_name = models.CharField(max_length=256, blank=True, null=True, db_comment="Name of the company in English.")
    # enAddressOutside from xml, address of the company outside of Japan in English.
    en_address_outside = models.CharField(max_length=128, blank=True, null=True, db_comment="Address of the company outside of Japan in English.")
    # furigana from xml, syllabic writing of the company name.
    furigana = models.CharField(max_length=256, blank=True, null=True, db_comment="Syllabic writing of the company name.")
    # hihyoji from xml, hidden or not.
    hihyoji = models.BooleanField(db_comment="Hidden or not.")

    # Prefecture (region of Japan) and city of the company.
    prefecture = models.ForeignKey("Prefectures", models.DO_NOTHING, blank=True, null=True, db_comment="Prefecture (region of Japan) of the company.")
    city = models.ForeignKey(Cities, models.DO_NOTHING, blank=True, null=True, db_comment="City of the company.")

    created_at = models.DateTimeField(blank=True, auto_now_add=True, db_comment="Created at.")
    updated_at = models.DateTimeField(blank=True, auto_now=True, db_comment="Updated at.")

    class Meta:
        db_table = "corporations"

        # Add indexing to improve performance.
        indexes = [
            models.Index(fields=[
                "number",
                "name",
            ])
        ]

    def __str__(self):
        return self.name

    @property
    def address(self):
        not_available = "N/A"
        return "{prefecture}; {city}; {street_number}; 〒 {post_code}".format(
            prefecture=self.prefecture.name if self.prefecture else not_available,
            city=self.city.name if self.city else not_available,
            street_number=self.street_number if self.street_number else not_available,
            post_code=self.post_code if self.post_code else not_available,
        )


class DynamicHTMLCode(models.Model):
    class HTMLCodeType(models.TextChoices):
        UPPER_RUNNING_TITLE_FOR_HOME_PAGE = "upper_running_title_for_home_page", "Upper running title for home page"
        LOWER_RUNNING_TITLE_FOR_HOME_PAGE = "lower_running_title_for_home_page", "Lower running title for home page"

    name = models.CharField(max_length=50, unique=True)
    type = models.CharField(max_length=50, choices=HTMLCodeType.choices)
    code = models.TextField(validators=[code_validator])
    enabled = models.BooleanField(default=True)
    expires_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "dynamic_html_code"
        ordering = [F("created_at").asc()]

    def __str__(self):
        return f"{self.code[:50]}..."

backend/search_engine/forms.py
from django import forms

from search_engine.models import Prefectures


class SearchForm(forms.Form):
    # TODO: Search as user types and remove submit button.
    search_field = forms.CharField(max_length=256, required=False, label="", help_text="Search by number, name or address.")


class ButtonCheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    template_name = "search_engine/widgets/button_checkbox_select.html"
    option_template_name = "search_engine/widgets/button_checkbox_option.html"

    # class name for input tag
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.attrs["class"] = "btn-check me-2"
        self.attrs["autocomplete"] = "off"


class TagsMultipleChoiceField(forms.MultipleChoiceField):
    widget = ButtonCheckboxSelectMultiple()


class PrefectureForm(forms.Form):
    prefecture = TagsMultipleChoiceField(
        choices=[
            (f"{prefecture.code}", f"{prefecture.name} ({prefecture.en_name})" if prefecture.en_name else f"{prefecture.name}")
            for prefecture in Prefectures.objects.all()
        ],
        required=False,
        label="",
        help_text="Search by prefecture.",
    )

backend/search_engine/views.py
import json

from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views import View

from .forms import SearchForm, PrefectureForm
from .mixins import DynamicHtmlMixin
from .models import Corporations, DynamicHTMLCode
from data_statistics.models import Statistics


class HomeView(View, DynamicHtmlMixin):
    dynamic_html_types = [
        DynamicHTMLCode.HTMLCodeType.UPPER_RUNNING_TITLE_FOR_HOME_PAGE,
        DynamicHTMLCode.HTMLCodeType.LOWER_RUNNING_TITLE_FOR_HOME_PAGE,
    ]

    def get(self, request):
        search_form = SearchForm(data=request.GET)

        # Get statistics.
        last_update = Statistics.objects.filter(type=Statistics.StatisticType.LAST_UPDATE).first().value
        updated_corporations_count = Statistics.objects.filter(type=Statistics.StatisticType.LAST_UPDATED_CORPORATIONS_COUNT).first().value

        corporations = Corporations.objects.all()
        if search_form.is_valid() and search_form.cleaned_data["search_field"]:
            corporations = Corporations.objects.all().filter(
                Q(number=search_form.cleaned_data["search_field"]) |
                Q(name__contains=search_form.cleaned_data["search_field"]) |
                Q(en_name__contains=search_form.cleaned_data["search_field"]) |
                Q(prefecture__name__contains=search_form.cleaned_data["search_field"]) |
                Q(city__name__contains=search_form.cleaned_data["search_field"]) |
                Q(street_number__contains=search_form.cleaned_data["search_field"]) |
                Q(post_code__contains=search_form.cleaned_data["search_field"])
            )

        page = request.GET.get("page", 1)
        paginator = Paginator(corporations, request.GET.get("page_size", 10))
        page_obj = paginator.get_page(page)

        return render(
            request,
            template_name="search_engine/corporations_list.html",
            context=self.get_context_data(
                search_form=search_form,
                page_obj=page_obj,
                last_update=last_update,
                updated_corporations_count=updated_corporations_count,
            ),
        )


class CorporationView(View):
    def get(self, request, corporation_number):
        corporation = get_object_or_404(Corporations, number=corporation_number)

        return render(
            request,
            template_name="search_engine/corporation.html",
            context={
                "corporation": corporation,
            },
        )


class FavoriteCorporationView(View):
    def get(self, request):
        # Get user`s favorite corporations from cookies (NOT SESSION).
        favorite_corporations = [int(corporation) for corporation in self.request.COOKIES.get("favoriteCorps", "").split(",") if corporation != ""]
        corporations = Corporations.objects.filter(number__in=favorite_corporations)

        page = request.GET.get("page", 1)
        paginator = Paginator(corporations, 20)
        page_obj = paginator.get_page(page)

        return render(
            request,
            template_name="search_engine/favorite_corporations_list.html",
            context={
                "page_obj": page_obj,
            },
        )


# Is not used yet, maybe in the future.
class PrefectureSearchView(View):
    def get(self, request):
        search_form = PrefectureForm(data=request.GET)
        corporations = Corporations.objects.all()
        if search_form.is_valid() and search_form.cleaned_data["prefecture"]:
            corporations = corporations.filter(prefecture__code__in=search_form.cleaned_data["prefecture"])

        # Pagination.
        page = request.GET.get("page", 1)
        paginator = Paginator(corporations, 20)
        page_obj = paginator.get_page(page)

        return render(
            request,
            template_name="search_engine/corporations_list_by_prefecture.html",
            context={
                "search_form": search_form,
                "page_obj": page_obj,
            },
        )

backend/search_engine/templates/search_engine/base.html
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}sha.wiki{% endblock %}</title>
        {% block css %}
            {% bootstrap_css %}
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg border-body navbar-light bg-light mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'search_engine:home' %}">sha.wiki</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link {% if request.resolver_match.url_name == 'favorite_corporations' %}active{% endif %}" href="{% url 'search_engine:favorite_corporations' %}">Favorites</a>
                        <a class="nav-link {% if request.resolver_match.url_name == 'statistics' %}active{% endif %}" href="{% url 'data_statistics:home' %}">Statistics</a>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container mb-5">
            {% block content %}
            {% endblock %}
        </div>

        <div>
            {% block modals %}
            {% endblock %}
        </div>

        {% block javascript %}
            {% bootstrap_javascript %}
            <script>
                const CORPORATION_NUMBER_URL = "{% url 'search_engine:corporation' 0 %}";
            </script>
            <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

backend/search_engine/templates/search_engine/corporation.html
{% extends "search_engine/base.html" %}

{% load bootstrap5 %}

{% block content %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="#main-info" data-bs-toggle="tab">法人番号 (Main info)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#statistics" data-bs-toggle="tab">全国{{ corporation.number }}位 (Statistics)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#geolocation" data-bs-toggle="tab">所在地 (Geolocation)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#siteInfo" data-bs-toggle="tab">サイト情報 (SiteInfo)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#media" data-bs-toggle="tab">報道での引用 (Media)</a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active d-flex justify-content-center" id="main-info">
        </div>
        <div class="tab-pane" id="statistics"></div>
        <div class="tab-pane" id="geolocation">
            <strong>Coming soon...</strong>
        </div>
        <div class="tab-pane" id="siteInfo">
            <strong>Coming soon...</strong>
        </div>
        <div class="tab-pane" id="media">
            <strong>Coming soon...</strong>
        </div>
    </div>
{% endblock %}

backend/search_engine/templates/search_engine/corporations_list.html
{% extends "search_engine/base.html" %}

{% load bootstrap5 %}
{% load static %}
{% load corporation_tags %}

{% block content %}
    {% block filter_forms %}
        {% if search_form %}
            <form action="" method="get">
                {% bootstrap_form search_form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Search</button>
                {% endbuttons %}
            </form>
        {% endif %}
    {% endblock %}

    {% block short_statistic %}
        <div class="row mb-3">
            {% for code_obj in dynamic_html.upper_running_title_for_home_page %}
            {{ code_obj.code|safe }}
            {% endfor %}
        </div>

        <div class="row mb-3">
            <p>
                <strong>Last updated:</strong> {{ last_update }}
            </p>
            <p>
                <strong>Companies updated:</strong> {{ updated_corporations_count }}
            </p>
        </div>

        <div class="row mb-3">
            {% for code_obj in dynamic_html.lower_running_title_for_home_page %}
                {{ code_obj.code|safe }}
            {% endfor %}
        </div>
    {% endblock %}

    {% block pagination %}
        {% if page_obj.paginator.count == 0 %}
            <p>No results found.</p>
        {% else %}
            <div class="row mb-3">
                {% page_size_selector page_obj url=request.get_full_path %}
            </div>

            <div class="row row-cols-1 row-cols-md-1 g-4 mb-3">
                {% for corp in page_obj.object_list %}
                    <div class="col">
                        {% corporation_card corp %}
                    </div>
                {% endfor %}
            </div>
            {% if page_obj.paginator.num_pages > 1 %}
                {% bootstrap_pagination page_obj justify_content="center" url=request.get_full_path %}
            {% endif %}
        {% endif %}
    {% endblock %}
{% endblock %}

{% block modals %}
    {{ block.super }}
    {% include "search_engine/modals/share_corporation.html" %}
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'search_engine/js/favorite_button.js' %}"></script>
    <script src="{% static 'search_engine/js/share_button.js' %}"></script>
{% endblock %}

backend/search_engine/templates/search_engine/corporations_list_by_prefecture.html
{% extends "search_engine/corporations_list.html" %}

{% load static %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'search_engine/js/button_checkbox_options.js' %}"></script>
{% endblock %}

backend/search_engine/templates/search_engine/favorite_corporations_list.html
{% extends "search_engine/corporations_list.html" %}

{% block short_statistic %}{% endblock %}

backend/search_engine/templates/search_engine/statistics.html
{% extends "search_engine/base.html" %}

{% load static %}

{% block title %}Statistics{% endblock %}

{% block content %}
    <p>
        <strong>Corporations amount:</strong> {{ corporations_amount }}
    </p>
    <p>
        <strong>Prefectures amount:</strong> {{ prefectures_amount }}
    </p>
    <p>
        <strong>Corporations tops:</strong>
    </p>
    <div class="accordion" id="corporationsTop">
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#youngestCorporationsCollapse" aria-expanded="true" aria-controls="collapseOne">
                    Youngest corporations
                </button>
            </h2>
            <div id="youngestCorporationsCollapse" class="accordion-collapse collapse show" data-bs-parent="#corporationsTop">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Creation date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for corporation in youngest_corps %}
                        <tr>
                            <td>{{ corporation.name }}</td>
                            <td>{{ corporation.change_date }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#oldestCorporationsCollapse" aria-expanded="true" aria-controls="collapseOne">
                    Oldest corporations
                </button>
            </h2>
            <div id="oldestCorporationsCollapse" class="accordion-collapse collapse" data-bs-parent="#corporationsTop">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Creation date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for corporation in oldest_corps %}
                        <tr>
                            <td>{{ corporation.name }}</td>
                            <td>{{ corporation.change_date }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#longestNamesCorporationsCollapse" aria-expanded="true" aria-controls="collapseOne">
                    Corporations with longest names
                </button>
            </h2>
            <div id="longestNamesCorporationsCollapse" class="accordion-collapse collapse" data-bs-parent="#corporationsTop">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Length</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for corporation in longest_names_corps %}
                        <tr>
                            <td>{{ corporation.name }}</td>
                            <td>{{ corporation.name|length }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#foreignAddressCorporationsCollapse" aria-expanded="true" aria-controls="collapseOne">
                    Corporations with foreign address
                </button>
            </h2>
            <div id="foreignAddressCorporationsCollapse" class="accordion-collapse collapse" data-bs-parent="#corporationsTop">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Address</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for corporation in foreign_address_corps %}
                        <tr>
                            <td>{{ corporation.name }}</td>
                            <td>{{ corporation.address_outside }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#mostChangesCorporationsCollapse" aria-expanded="true" aria-controls="collapseOne" disabled>
                    <i>
                        Corporations with most changes (Coming soon)
                    </i>
                </button>
            </h2>
            <div id="mostChangesCorporationsCollapse" class="accordion-collapse collapse" data-bs-parent="#corporationsTop">
                <div class="accordion-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Changes amount</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for corporation in most_changes_corps %}
                        <tr>
                            <td>{{ corporation.name }}</td>
                            <td>{{ corporation.changes_amount }}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}